<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 07.01.19
 * Time: 12:13
 */

interface iUnit{
}

abstract class unit implements iUnit {

    protected $device = null;
    private $type = typeUnit::NONE;

    /**
     * unit constructor.
     */
    public function __construct($type, array $device)
    {
        $this->type = $type;
        $this->device = managerDevices::createDevice($device);
    }

    public function __destruct()
    {
        unset($this->device);
    }

}

class sensorUnit extends unit
{

    /**
     * sensorUnit constructor.
     */
    public function __construct(array $options, $type)
    {
        $sel = new selectOption();
        $sel->set('DeviceID', $options['DeviceID']);
        $arr = DB::getListDevices($sel);
        parent::__construct($type, $arr[0]);
    }

    public function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }
}

class moduleUnit extends unit
{

}

class iButtonUnit extends unit
{

}

class temperatureUnit extends sensorUnit {

    public function __construct(array $options) {
        parent::__construct($options, typeUnit::TEMPERATURE);
    }

    public function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }

    public function getValue()
    {
        return $this->device->getValue();
    }

}
